### PR TITLE
Feature/longer strings

### PR DESCRIPTION
**Pull request by SamCoVT**
I believe I've handled all of the outstanding long-string support issues (#19 #20 #21 #22 #67 #68) in this pull request.  If there are still any string-handling words that weren't in the issues tracker, they should still work fine on strings of 255 and less characters because I didn't end up changing the storage format in the dictionary.

In pretty much all of the cases, I replaced ,y type addressing with zero page indirect addressing, having to update the 16-bit pointers as I moved along.  

The copying of a string into the dictionary moved from `SLITERAL` to `S_QUOTE`.

This code passes all of the string tests, but I didn't add any extra tests specifically for very long strings.

### CODE REVIEW

**Comment by scotws** [comment]
Cool - that's a lot of issues at once! It's going to be a day or two before I'll have time sit down at the computer again, but definitely will aim for early this week.

**Comment by SamCoVT** [comment]
I haven't figured out how to have github make a pull request that only has the diff I want without all of the previous diffs in there too.  If you know how to do this (or can point me towards a tutorial), I'd like to know.  If I can figure that out, I can make more, smaller, pull requests as I am working on something.

In the meantime, check out my pull request for bugfix/accept when you do get some computer time.  It has all of this plus a fix for ACCEPT and long strings as well.

**Comment by SamCoVT** [comment]
You may want to hold off merging this pull request.  I'm having issues getting this running properly on real hardware (crashes hard, requiring reset).  I can't reproduce the issue in the py65mon emulator, so I'm not sure if it's a problem with the new code or some kind of hardware issue.  I also didn't play much with strings the last time I got Tali2 running on hardware, so I don't know if it's pre-existing or not.

It seems to crash right after:

Receiving the ending quote for any size s" string (but not always - sometimes it works fine)

Receiving more than 255 characters in a s" string (gacks in the middle of the string and prints a few unprintable characters and then stops).  It often seems to accept the first 255 fine and then gacks after the second or third 255.


Looking at the dictionary RAM after a reset shows that all of the characters typed in up to that point are in the dictionary, which makes me think it might be in S".

I plan to check out some older versions of Tali and assemble them for my hardware to see if I can locate the issue.  My main thoughts are:

py65mon has 0s in unused memory, while I have random bits.

I might have used an invalid addressing mode that Ophis and py65mon think works, but doesn't on real hardware

I may be overflowing my serial hardware and somehow getting into a state where new bytes aren't accepted.  Once 255 bytes have come in, Tali has to process them all and get them in the dictionary before the next byte arrives, and my hardware runs at only 1MHz.

**Comment by SamCoVT** [comment]
And.... it's fine.  I forgot to move the end of RAM down because my I/O on my hardware is in $7F00-7FFF.  When the last history buffer was being written to, it was overwriting the settings in my ACIA, which would totally explain the "crashing" I saw.  Tali was running fine, but I couldn't talk to it anymore until I hit the reset button to reinitialize my ACIA.

It seems to work fine on my hardware now.

**Comment by scotws** [comment]
Really cool, you got rid of a lot of stuff there in one swoop. Thanks!

**Pull request merged**
