### PR TITLE
Added facility to time cpu cycles of words with initial tests to demo

### PR DESCRIPTION
**Pull request by SamCoVT**
Initial demo for #55.
By "assembling" (really, just stuffing some opcodes in the xt) the begin_cycle and end_cycle words, I was able to get the overhead down to just 16 cycles as long as they are compiled.  If you run them in interpreted mode, there's almost 1200 cycles of overhead.  Here's an example run from the demo .fs file (cycles.fs) included with this modification to the tester:
```
\ Determine the overhead of the testing words themselves.  ok
: cycles_overhead begin_cycles end_cycles ;  ok
cycles_overhead  CYCLES: 16  ok
  ok
\ Test a word.  ok
: cycles_/ 1234 7 begin_cycles / end_cycles ;  ok
cycles_/  CYCLES: 1520  ok
  ok
\ Test a word with lookup overhead.  ok
begin_cycles end_cycles ( overhead )  CYCLES: 1198  ok
1234 7 begin_cycles / end_cycles ( actual test )  CYCLES: 4665  ok
  ok
\ Test what should be a very small word.  ok
: cycles_drop 5 begin_cycles drop end_cycles ;  ok
cycles_drop  CYCLES: 25  ok
```

The file cycles.fs will need to be filled in with sample timing tests for all the words you are interested in.

Currently it's only the test program that can see the cycles.  They are printed into the results file and to the screen, but Tali doesn't know it's happening.  If you want a more advanced mode of operation, I could make them available (at specific memory addresses) so that Tali could time itself.  That, for example, would allow Tali to subtract the overhead (constant when the test words are compiled in).

### CODE REVIEW

**Comment by scotws** [comment]
Okay, I'll have to come back to this one tonight to play around with it. Having Tali time itself sounds a bit weird at first glance (and possibly illegal in some states), but given that this is Forth, which tends to do stuff like that, it could make very good sense.

**Comment by SamCoVT** [comment]
I tried fetching this to a windows machine, and discovered that I forgot to add the cycles.fs file.  I'll have to add it this evening when I'm back at my main development machine.  Sorry for the inconvenience.  In good news, though, I was able to upgrade my copy of py65 via pip and run the test program (minus the cycle count) on Windows.

**Comment by SamCoVT** [comment]
I've updated the test program so it makes the results available to Tali.  I ran into an issue where the memory right after the 0xF001 and 0xF004 addresses was already in use, so I put the result higher up.  I think I want to move all of the addresses for this together eventually.  Right now the "start timing" address is 0xF002, the "stop timing" address is 0xF003, and the results show up (as a double word) at 0xFF00.

Do you think it makes sense to actually test the timing results (using the { --> } test system) or just report them?  If we test them, we'd have to update the cycles.fs every time we modify words.  If we just report them, then we'd have to look at the testing diffs (and I'll need to fix the testing order #94 with cycles.fs run last).

**Comment by scotws** [comment]
Good points, you right that it makes sense to see what we can do here for the moment and then see if we have to, er, escalate later. Included conversion to list from frozenset. -- is there a special reason why the double goes to $FF00?

**Comment by SamCoVT** [comment]
You had asked why the double timing result is at $FF00 while the start/stop locations were between the IO memory locations as $F002 and $F003.  I wanted to put the double starting at $F006 (an even numbered address), but there was already code there (the reset vector says to start running there, if I remember correctly).  I arbitrarily picked what looked like a free spot that was away from other code.

I would like to move the start/stop/results locations together somewhere in the memory map.  I think we want to leave the I/O where it is at $F001 and $F004 so Tali will work out of the box on a stock py65mon emulator.

I'll create a separate issue for moving the timing stuff together.  It works for right now, but I would like to "betterize" it.

**Pull request merged**
