### PR TITLE
Feature/blocks

### PR DESCRIPTION
**Pull request by SamCoVT**
Initial block support needed to start writing the block editor.  This includes a RAM drive for playing with in py65mon as well as for use by the tester.  This includes tests for the basic BLOCK words.  Some words still need specific tests.  I added a chapter to the manual discussing how to use the block words and how to create the ram drive if not using real hardware.

I also added a section in the manual for the editor(s?) and gave the Forth code for the screen editor I'm currently using.  It allows the user to enter either a single line or an entire screen, replacing the original contents.  I don't plan on adding the fiddly "move 3 chars to the left" kind of editing, as you can just replace the line and use your terminal's copy/paste for the parts you want to keep.  Eventually this will be incorporated into Tali, but for now it shows some code that uses the block words.

### CODE REVIEW

**Comment by scotws** [comment]
Now that's a lot of work :-)! It's going to take me a bit to go through everything. At first glance: 

- You have two styles for Forth words, one with a dash between the words and now some with underscores (**block_words_deferred** for instance). Honestly I don't think it makes any difference, but I wondering if we should stick to dashes for everything following **PARSE-NAME** ANS words style.
- I've never seen any Forth code structured like **block_init_ramdrive** -- really cool idea, solves the problem of not defining words until it is time. Your invention?
- We should probably update **EVALUATE** to your version quickly to get rid of the "redefined" error message. Again, that was where I cut corners.

Thanks again for all the work!

**Comment by SamCoVT** [comment]
I agree on the naming issue.  I also noticed that you had mentioned **BLOCK-READ** and **BLOCK-WRITE** and I forgot the dash when I wrote them.  I think I want to put the dash in, as it makes a BLOCK-* family of words.  I'd also like to rename **block_init_ramdrive** to **BLOCK-RAMDRIVE-INIT** and perhaps rename **RAMDRIVE** to **BLOCK-RAMDRIVE**.  Would you prefer the names were in lowercase in both the implementation and the documentation?

If you want to leave this open, I'll do a little more work on it.  I'll need to update the documentation and tests as well.  I'm also open to suggestions about the names of words to use for the editor.  **LIST** is defined by the standard, but everything else is up for debate.  Once we have word lists, we can compartmentalize some of these word sets.

The block_init_ramdrive I came up with myself, and I figured out how to do it while running evaluate on strings inside blocks (to make sure BLK was set to zero when evaluating the string, but went back to the block number when returning to the block).  It seems a little silly that your big string in ROM has another string put into RAM that is then evaluated when the user asks for it, but it works.

I was also super happy that I actually got to use **CREATE** and **DOES>**, and even figured out how to do it properly (I think).  I saw your mention of **BUFFER:** and I don't mind writing that word and then creating the ram drive with it.  I'll just need to move the "DOES>" section into the block-read-ramdrive and block-write-ramdrive routines.  That may make it easier for newbies to grok if they decide to look under the hood.

Updating **EVALUATE** is tricky.  The issue is that it doesn't know if it's processing a string, or if it was given the address of a line in a block and a length of 64.  It can't tell the two apart.

They way it works now is that when you **LOAD**, the block number is stored in **BLK** and then the OLD version of **EVALUATE** is run (which saves everything else - it just doesn't know about the number in **BLK**.  Once **LOAD** is done with the block, it restores the previous value of **BLK** (in case we were loaded from another block) and then calls **BLOCK** again if the previous value of **BLK** was not zero.

After I have written **LOAD** using the old version of **EVALUATE**, I then modify **EVALUATE** to always store a 0 into **BLK** first, per the standard, before processing a string (and I restore **BLK** afterwards).

The issue is that **LOAD** needs a version of **EVALUATE** that doesn't mess with the value in **BLK**, but ultimately **EVALUATE** needs to put a 0 into **BLK** when processing strings.  I made this happen by redefining **EVALUATE** _AFTER_ using it in LOAD, and I was super happy when I figured out I could do it that way.

Ultimately I need one version of evaluate that sets BLK to 0 for strings and another that sets it to the block number for blocks.  

If we assemblerize LOAD, then I can call into a separate label in EVALUATE (after it has set **BLK** to zero), because the rest of the code should work.  I'll just have to make sure the cleanup at the end works for both situations.  Perhaps that's our ultimate path forward.

**Comment by SamCoVT** [comment]
I hope you don't mind me sneaking one more commit in here.  I was looking at the code for xt_backslash and I realized that it SHOULD work when using **LOAD** on a screen, and when I tested it, it does!  I've just removed the note in the manual to only use **( )** comments in screens, because \\ works fine too.  If you see anything else you would like fixed up or done differently, let me know.

I also have to apologize for what looks like double or triple commits - I had to rebase on the master branch to get the fix for EVALUATE in here, and then I had to merge one of my other branches.  I think I should have done all of that locally before I pushed it up to my github, so unfortunately its messy history is here for all to see.

**Comment by scotws** [comment]
Don't worry about the commits or lots of comments for that matter, I have this paranoid thing about committing after certain stages so mine are messy as well. -- For the documentation, at some point we'll probably need some sort of a style guide given the amounts we have here now, but for the moment, lowercase in code is more important and the rest we'll figure out later. Now off to blocks!

**Pull request merged**
